### ISSUE TITLE
"Data source" disciplines - suggestion to use Topic entity.

### ISSUE THREAD

**Issue by rduyme** [skg-if/interoperability-framework#13]
"Data source" disciplines - suggestion to use Topic entity. https://skg-if.github.io/interoperability-framework/data-source

For flexibility, we could link topic the same way it is done in Research product. https://skg-if.github.io/interoperability-framework/research-product

There are other big standard for science topics :
* Library of Congress Classification : https://id.loc.gov/authorities/classification
* FOR Fields of Research (ANZSRC 2020, australia, new zealand classification) https://plus.dimensions.ai/support/solutions/articles/23000018820-which-research-categories-and-classification-schemes-are-available-in-dimensions- (used in dimensions)
* Austrian Fields of Science and Technology Classification 2012  : https://vocabs.dariah.eu/oefos/en/
* FOS is used in OpenAire : https://explore.openaire.eu/fields-of-science
* I think there is one for EU as well
...

A few other examples in Clarivates/Incites for general classifications 
![image](https://github.com/user-attachments/assets/be4cd565-510f-49df-907f-5f3838d3384c)

**Comment by essepuntato** [comment]
The topics specified in a research product may vary a lot in the content – indeed, as written in the doc, they are "disciplines, subjects and keywords potentially relevant for a Research product", while the disciplines in the data source are just disciplines. In addition, there is an explicit requirement of refer to all of them, if needed, which is something that is not managed currently when we refer to topics.

Just to clarify here, we do already use the Library of Congress Classification in the terms for the disciplines since it is already available and standard, has excellent coverage and is already a Linked Open Data implementation.
