### ISSUE TITLE
Agent hierarchy

### ISSUE THREAD

**Issue by chenejac** [skg-if/interoperability-framework#16]
There might a mistake in [the list of subclasses of the Organization class](https://github.com/skg-if/data-model/blob/main/graphs/skg-if-agent.png). Repository and Facility probably shouldn't be a subclass of the class Organization.

**Comment by essepuntato** [comment]
This is something we have clarified in some of the previous meetings, but yes, a book can be, at the same time, a research product and a venue for other research products (e.g. chapters). This does not violate any particular semantic rule since the same object can have different roles depending on the context (e.g. a person being an author for one paper and an editor for another).

**Comment by rduyme** [comment]
Totally agree, this was clarified, I suggest we add a few lines to the definition, to nail the concept forever :-) 

Here  is update of the current definition I suggest.
"A Venue is an entity that models a publishing “gateway” used by an Agent to make their Research products available to others.
Venue are defined with an editorial point of vue. 
- A scholarly journal is a typical example of Venue for Research Product Literature
- A Dataset catalog is a typical example of Venue for Research Product Data

Depending on the context an entity can be represented as a Venue or a Research product. A book is one of these specific entities "

**Comment by andremann** [comment]
Address in 738d86c
