### ISSUE TITLE
Understand what happeneded to product.manifestations.metadata_curation while porting to json-ld

### ISSUE THREAD

**Issue by andremann** [skg-if/interoperability-framework#6]

**Comment by essepuntato** [comment]
Just checked in the notes I had, and the point is the following. First, I think it was directly attached to the research product, not to its manifestation. Second, it is unclear what does it mean. Reading the old documentation, I read "Whether the Research product has undergone a metadata curation process". Supposing that it's an article, does it mean that:

1. the publisher has curated its metadata?
2. has the source that provides the SKG-IF-compliant metadata curated the returned metadata?
3. other?

Since I did not see any precise definition there, I've put it in limbo – and then forgot to highlight the problem. I think we should understand carefully if we need it or not. In particular, to what question are we answering with that information? Is it crucial for all the sources involved so far?
